resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/mbhave/concourse-demo-library.git
    branch: master
jobs:
- name: build
  plan:
  - get: git-repo
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8-jdk-alpine
      inputs:
      - name: git-repo
      run:
        path: git-repo/ci/scripts/build.sh
