resource_types:
- name: artifactory-resource
  type: docker-image
  source:
    repository: springio/artifactory-resource
    tag: 0.0.4
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/mbhave/concourse-demo-library.git
    branch: master
- name: artifactory-repo
  type: artifactory-resource
  source:
    uri: ((artifactory-server))
    username: ((artifactory-username))
    password: ((artifactory-password))
jobs:
- name: build
  plan:
  - get: git-repo
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8-jdk-alpine
      inputs:
      - name: git-repo
      run:
        path: git-repo/ci/scripts/build.sh
