resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/mbhave/concourse-demo-library.git
    branch: master
jobs:
- name: build
  plan:
  - get: git-repo
    trigger: true
  - task: build
    file: git-repo/ci/tasks/build.yml